version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/pentago
    command: bash -c "python3 ./pentago.py"
    working_dir: /usr/pentago
